// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Phub.Infrastructure.Persistence;

#nullable disable

namespace Phub.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260503120000_AddShopCipherToConnection")]
    partial class AddShopCipherToConnection
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
