<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Phub.Application\Phub.Application.csproj" />
    <ProjectReference Include="..\..\src\Phub.Infrastructure\Phub.Infrastructure.csproj" />
  </ItemGroup>
</Project>
