// <auto-generated />
using System.Reflection;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Sabr.Infrastructure.Persistence;

#nullable disable

namespace Sabr.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260401145000_SeedAiPrompts")]
    partial class SeedAiPrompts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // This migration seeds data only, so it reuses the target model from the
            // immediately previous schema migration.
            var previousMigration = new AddListingDraftWarrantyAndShipping();
            var buildTargetModel = typeof(AddListingDraftWarrantyAndShipping).GetMethod(
                "BuildTargetModel",
                BindingFlags.Instance | BindingFlags.NonPublic);

            buildTargetModel!.Invoke(previousMigration, new object[] { modelBuilder });
        }
    }
}
